import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/dist/client/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gradient-to-br from-pink-400/90 via-pink-300 to-gray-300`}
      ><nav className="flex items-center justify-between px-10 py-2 bg-white/30 backdrop-blur-md shadow-md sticky top-0 z-50">
        <a href="/">
        <h1 className="text-4xl font-extrabold bg-gradient-to-r from-pink-400 via-pink-500 to-pink-600 bg-clip-text text-transparent  ">Aura</h1>
        </a>
        <div className="flex gap-8 text-gray-800 border-b border-gray-900/20 text-sm ">
          <Link href="/" className="hover:text-pink-500 transition md:text-lg">
            Home
          </Link>
          <Link href="/product-page" className="hover:text-pink-500 transition md:text-lg">
            Products
          </Link>
          <Link href="/faq" className="hover:text-pink-500 transition md:text-lg">
            FAQ
          </Link>
        </div>
        <Link href="/cart">
          <img src="/263142.png" alt="cart" className="w-6 h-6 object-contain" />
        </Link>
      </nav>

        {children}
 <footer className="text-center py-4 text-gray-600 bg-white/30 backdrop-blur-md shadow-md">
          &copy; 2024 MyStore. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
